quotes_list = ["May the force be with you",
"I'm a Mandalorian. Weapons are part of my religion. — Mando",
"Your focus determines your reality. — Qui-Gon Jinn",
"It's a trap! - Admiral Ackbar",
"I have a very bad feeling about this. - Luke Skywalker",
"There's always a bigger fish. — Qui-Gon Jinn",
"Never underestimate a droid. — General Leia Organa",
"Women always figure out the truth. Always. — Han Solo",
"You were my brother, Anakin! I loved you! - Obi-Wan Kenobi",
"This is the way. — Mando",
"In my book, experience outranks everything. — Captain Rex",
"These aren't the droids you're looking for. — Obi-Wan Kenobi",
"Strike me down and I will become more powerful than you could possibly imagine. — Obi-Wan Kenobi",
"I find your lack of faith disturbing. — Darth Vader",
"Let the wookie win. — C-3PO",
"Do or do not. There is no try. — Yoda",
"Yeah, I'm responsible these days. It's the price you pay for being successful. — Lando Calrissian",
"Never tell me the odds! — Han Solo",
"Many of the truths that we cling to depend on our point of view. — Obi-Wan Kenobi",
"I've found that what most people call luck is often little more than raw talent combined with the ability to make the most of opportunities. — Talon Karrde",
"Reality doesn't care if you believe it. — Boba Fett",
"Life is not without pain, but life concerns itself with how we handle that pain, or joy, or confusion, or triumph. Life is more than time passing before death; it is the sum and total of all we make of it. — Elegos A’Kla",
"You can't stop the change, any more than you can stop the suns from setting. — Shmi Skywalker",
"Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering. — Yoda",
"The ability to speak does not make you intelligent. — Qui-Gon Jinn",
"Your focus determines your reality. — Qui-Gon Jinn",
"You feel empty. You feel alone. Lonely. Almost frightened, but also strong, yes? The name for what you are feeling is freedom. How did you expect it to feel? You are free, and that can be lonely, and empty, and frightening. But it is also powerful. — Jedi Master Vergere",
"Lesson one from this experience: Realize how much you don't know. Lesson two: Make sure to learn from lesson one. — Jacen Solo",
"Sometimes we must let go of our pride and do what is requested of us. — Padmé Amidala",
"This threshold is mine. I claim it for my own. Bring on your thousands, one at a time or all in a rush. I don't give a damn. None shall pass. — Gannar Rhysode",
"Inevitably, love is going to lead to as much sorrow and regret as it does joy. How you deal with the bad part of love determines your character, what determines the dark side's hold over you. — Jolee Bindo",
"Who I am is not important, my message is. — Darth Revan",
"Advice: Any organic who lives within their means suffers from a lack of imagination. — HK-47",
"We fight for justice because justice is the fundamental bedrock of civilization: An unjust civilization is built upon sand. It does not long survive a storm. — Mace Windu",
"To be united by hatred is a fragile alliance at best. — Kreia",
"There is nothing wrong with fear. You need never be ashamed of it, as long as it doesn't stop you functioning. Fear is your natural warning system; it keeps you alive so that you can fight. Show me a man who isn’t afraid and I’ll show you a fool who is a danger to his entire ship. — Admiral Adar Tallon",
"So this is how liberty dies ... with thunderous applause. — Queen Amidala",
"Train yourself to let go of everything you fear to lose. — Yoda",
"The dark is generous, and it is patient, and it always wins — but in the heart of its strength lies its weakness: One lone candle is enough to hold it back. Love is more than a candle. Love can ignite the stars. — Narrator",
"The bigger the galaxy, the sweeter the homecoming. — Corellian proverb",
"Easy is the path to wisdom for those only not blinded by themselves. — Broadside",
"It's every citizen's duty to challenge their leaders, to keep them honest, and hold them accountable if they're not. — Ahsoka Tano",
"Sometimes it takes courage to stick to one's beliefs, young Padawan. — Aayla Secura",
"Rule 23: Never pull sentry duty on an empty stomach. — Scorch",
"The winding path to peace is always a worthy one, regardless of how many turns it takes. — “Dooku Captured” moral",
"Nobody cares who your father was, only the father you'll be. — Mandalorian proverb",
"Sometimes to heal, you must first hurt. — Cilghal",
"If I trust the wrong guy, maybe I get hurt. But if I'm too scared to help someone who really needs it, who knows how many people will suffer? — Corso Riggs",
"An object cannot make you good or evil. The temptation of power, forbidden knowledge, even the desire to do good can lead some down that path. But only you can change yourself. — Bendu",
"If you define yourself by your power to take life, your desire to dominate, to possess, then you have nothing. — Obi-Wan Kenobi",
"The belonging you seek is not behind you; it is ahead. — Maz Kanata",
"As long as there's light, we've got a chance. — Poe Dameron",
"I know how to run without you holding my hand! — Rey",
"Let the past die. Kill it if you have to. — Kylo Ren",
"We have hope. Rebellions are built on hope. — Jyn Erso",
"I am one with the Force. The Force is with me. — Chirrut Îmwe",
"You're not the only one who lost everything. Some of us just decided to do something about it. — Cassian Andor",
"A tyrant can make anything seem to be the will of the people.'  — Senator Leia Organa",
"Good intentions aren't enough. They're not meaningless, but that's where we have to start, not where we end. — Princess Leia",
"Authority can be given, but leadership must be earned. — Queen Breha Organa",
"That's how we're gonna win. Not fighting what we hate, saving what we love. — Rose Tico",
"No one's ever really gone. — Luke Skywalker",
          
          ]